baseURL = "http://noelmrtn.fr/"
languageCode = "fr-FR"
title = "noelmrtn" 
theme = "noelmrtn-theme"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20